### PR TITLE
Added support for '$exists' operator

### PR DESCRIPTION
**Pull request by gisderdube**

### CODE REVIEW

**Comment by boblauer** [comment]
This shouldn't be necessary.  The `MongooseDateOnly` schema inherits from `mongoose.SchemaType`, which already specifies an `$exists` operator that works for `DateOnly`.

I confirmed this already works with two different tests:

```js
it('exists == true', function (done) {
  Record.create({ d: new DateOnly('1/1/2000') }, { d: undefined }, function (err) {
    assert.ifError(err);
    Record.find({ d: { $exists: true } }, function (err, records) {
      assert.ifError(err);
      assert.ok(records);
      assert.equal(records.length, 1);
      assert.equal(records[0].d.valueOf(), 20000001);
      done();
    });
  });
});

it('exists == false', function (done) {
  Record.create({ d: new DateOnly('1/1/2000') }, { d: undefined }, function (err) {
    assert.ifError(err);
    Record.find({ d: { $exists: false } }, function (err, records) {
      assert.ifError(err);
      assert.ok(records);
      assert.equal(records.length, 1);
      assert.equal(records[0].d, undefined);
      done();
    });
  });
});

**Comment by gisderdube** [comment]
Thanks for your answer. Unfortunately, it only worked for us only after adding `$exists` operator to `$conditionalHandlers`. I see your tests and they look fine. Any idea?
I got the error 

> Can not use $exists with DateOnly.

**Comment by boblauer** [comment]
What version of mongoose are you using?

**Comment by gisderdube** [comment]
v4.11.1

**Comment by boblauer** [comment]
What does your query look like?  I see the line that's telling you `Can not use $exists with DateOnly`, but for some reason my tests must not be going down that same code path.

**Comment by gisderdube** [comment]
```
...
{
  '$and': 
   [ { birthdate: { '$gte': 20161021, '$lte': 20161021 } },
     { is_member: true,
       '$or': 
        [ { leave_date: { '$gte': moment("2017-11-01T23:59:59.999") } },
          { leave_date: { '$exists': false } },
          { leave_date: null } ] } 
   ]
 }
```
you may ignore the first `leave_date` value, I changed it, but I guess it should not matter anyways.

**Comment by boblauer** [comment]
It is indeed a new change with mongoose 4.x.  Unfortunately your code doesn't work with mongoose 3.x.  I'll hopefully have something up soon, I'll let you know.

**Comment by gisderdube** [comment]
Ok, thanks a lot!

**Comment by boblauer** [comment]
Resolved and published to npm, `@1.0.4`.  Thanks for the pull!

**Pull request closed without merging**
